### ISSUE TITLE
IDE version 2024.3 not supported

### ISSUE THREAD

**Issue by radoslawkoziol** [dinbtechit/jetbrains-nestjs#13]
### What happened?

After updating the IDE to version 2024.3, the plug-in is no longer supported. I think it's simply a wrong assumption in the plug-in configuration itself, I don't think the new version of Storm has messed up the compatibility, so I'm reporting this as a bug.

### Steps to reproduce

Upgrade IDE to 2024.3

### Gradle IntelliJ Plugin version

1.16.0

### Gradle version

8.2.1

### Operating System

Windows

**Comment by dinbtechit** [comment]
> @dinbtechit I guess something went wrong ;) ![image](https://private-user-images.githubusercontent.com/10725188/389443720-9816d0e0-106b-4376-a5b6-3c2046021094.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDI2MjQsIm5iZiI6MTczMjU0MjMyNCwicGF0aCI6Ii8xMDcyNTE4OC8zODk0NDM3MjAtOTgxNmQwZTAtMTA2Yi00Mzc2LWE1YjYtM2MyMDQ2MDIxMDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDEzNDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMWJhYWU2YTIyMjg3ZGVlMjVkYjhlZWU3NWJlZGI0NzJjNzhiZTg0NjgyOTczNmY2NWJiNDEyMDFjMGNlOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oLGQupJTiYlPqO7wjC0WCY7k_FaADicG2rg_WihZjqc)

ugh. Fixed in v0.0.5
