### ISSUE TITLE
[Bug] - "OK" button persist disabled after empty filename input submit try, even if add filename later

### ISSUE THREAD

**Issue by knilsyansky** [dinbtechit/jetbrains-nestjs#4]
## Describe the bug
When creating a service or module with context menu new > nest service, when you press OK with an empty second input the error "filename required" appears and the OK button gets disabled. Even after adding a filename, the error and the disabling of the OK button persist.

## Platform
- IDE Details:  WebStorm 2024.1 EAP
Build #WS-241.8651, built on January 12, 2024
Licensed to WebStorm EAP user: Роман Knils
Expiration date: February 11, 2024
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-14-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 16384M
Cores: 4
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.github.dinbtechit.jetbrainsnestjs (0.0.2)
Current Desktop: ubuntu:GNOME

**Comment by dinbtechit** [comment]
@knilsyansky  Thank you for logging this bug. This will be fixed in the next release.

**Comment by dinbtechit** [comment]
@knilsyansky - Looks like this issue has been fixed. Please reopen if it is still an issue. Thanks


https://github.com/user-attachments/assets/1bc8507e-02b9-4e3a-8098-d5e20319188e
