### ISSUE TITLE
[Question] - Can I generate the service in the same module path?

### ISSUE THREAD

**Issue by n0isy** [dinbtechit/jetbrains-nestjs#5]
topic

![изображение](https://github.com/dinbtechit/jetbrains-nestjs/assets/8371968/e38e532a-b027-454f-9583-b345fd97b54f)
![изображение](https://github.com/dinbtechit/jetbrains-nestjs/assets/8371968/ffa0f4f7-9a4c-4e7d-823f-ec8f9fce16ec)

Expected:
![изображение](https://github.com/dinbtechit/jetbrains-nestjs/assets/8371968/c5fab5d7-9f66-404c-95e8-0e75427896e3)

**Comment by dinbtechit** [comment]
@n0isy - Sorry for the late response. Yes, you should use the `--flat` flag in the parameters in order to create the services at the root of the directory.

![image](https://github.com/dinbtechit/jetbrains-nestjs/assets/17984781/bcd39792-8fb8-4c08-92d3-734eb8fbe819)

> [!TIP]
> Take a look at other [Nest generate CLI ](https://docs.nestjs.com/cli/usages#nest-generate) options you can use.
