### ISSUE TITLE
[Bug] - can't work in pnpm workspace

### ISSUE THREAD

**Issue by morty6688** [dinbtechit/jetbrains-nestjs#8]
## Describe the bug

When right click on a nest project in pnpm workspace, it doesn't work

## Platform
- IDE Details:  IntelliJ IDEA 2024.2.3 (Ultimate Edition)
Build #IU-242.23339.11, built on September 25, 2024

**Comment by dinbtechit** [comment]
is this related to this bug? If so can you see if the workaround described here would work?

https://github.com/dinbtechit/jetbrains-nestjs/issues/2#issuecomment-1877508490

**Comment by morty6688** [comment]
> is this related to this bug? If so can you see if the workaround described here would work?
> 
> [#2 (comment)](https://github.com/dinbtechit/jetbrains-nestjs/issues/2#issuecomment-1877508490)

Oh thx! It does work now

**Comment by morty6688** [comment]
> is this related to this bug? If so can you see if the workaround described here would work?
> 
> [#2 (comment)](https://github.com/dinbtechit/jetbrains-nestjs/issues/2#issuecomment-1877508490)

Sorry, the menu item occurred, but it still can't work when I tried to create a new service. Cuz when I clicked the menu item, nothing happened.

**Comment by dinbtechit** [comment]
are you able to provide a screen recording demonstrating the issue?

**Comment by morty6688** [comment]
> are you able to provide a screen recording demonstrating the issue?
![anime](https://github.com/user-attachments/assets/82f02080-e5c6-448e-85f2-6fc1ce4d6b2b)
Sure, here is a gif

**Comment by dinbtechit** [comment]
interesting... Can you send me the following to resolve this issue?

1. IDE log:

> [!Important]
> Before copying the logs -> try creating the service/controller/module using the nestjs menu.

On MacOS: (This is how you can get the logs). I assuming it would be similar for other operating systems.

IDE -> Help (menu) -> Show log in Finder -> idea.log 

![image](https://github.com/user-attachments/assets/4b48f2d4-8ae8-4466-895a-b3fad1687c04)

2. Can you create a sample repo with similar folder structure?

**Comment by morty6688** [comment]
> interesting... Can you send me the following to resolve this issue?
> 
> 1. IDE log:
> 
> Important
> 
> Before copying the logs -> try creating the service/controller/module using the nestjs menu.
> 
> On MacOS: (This is how you can get the logs). I assuming it would be similar for other operating systems.
> 
> IDE -> Help (menu) -> Show log in Finder -> idea.log
> 
> ![image](https://private-user-images.githubusercontent.com/17984781/374569755-4b48f2d4-8ae8-4466-895a-b3fad1687c04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTM0NzQsIm5iZiI6MTcyODM5MzE3NCwicGF0aCI6Ii8xNzk4NDc4MS8zNzQ1Njk3NTUtNGI0OGYyZDQtOGFlOC00NDY2LTg5NWEtYjNmYWQxNjg3YzA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEzMTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNTBjNjYwMzg5MTY1MWFmMTVjNWYzMzY2NTkzNGFiYTY1NDY5NWNmMTY3NDZkZTIwNzExMzE4YjRkMzNjYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6dxfXWpP6asEScCqnHK_WLMEslU-NSQZ8AlBXR8icVg)
> 
> 2. Can you create a sample repo with similar folder structure?

[idea.log](https://github.com/user-attachments/files/17294009/idea.log)

OK，here is the log

**Comment by morty6688** [comment]
> interesting... Can you send me the following to resolve this issue?
> 
> 1. IDE log:
> 
> Important
> 
> Before copying the logs -> try creating the service/controller/module using the nestjs menu.
> 
> On MacOS: (This is how you can get the logs). I assuming it would be similar for other operating systems.
> 
> IDE -> Help (menu) -> Show log in Finder -> idea.log
> 
> ![image](https://private-user-images.githubusercontent.com/17984781/374569755-4b48f2d4-8ae8-4466-895a-b3fad1687c04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTQ5MTYsIm5iZiI6MTcyODM5NDYxNiwicGF0aCI6Ii8xNzk4NDc4MS8zNzQ1Njk3NTUtNGI0OGYyZDQtOGFlOC00NDY2LTg5NWEtYjNmYWQxNjg3YzA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEzMzY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZTBiOWQ5MmVmNDNlNWY4NTA5OTdmZTg0MzBlNDM4ZDdhM2I4Y2ExY2U2ODgzZjU3ZmMwYTgxYTU2YTkxNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wbvfAAoMGvxX8Fvpz6rpOb-WBdvV-s7R-xC1uhVrM1o)
> 
> 2. Can you create a sample repo with similar folder structure?

https://github.com/tomwray13/nestjs-nextjs-trpc, u can use this repo to test
and here is my log: [idea.log](https://github.com/user-attachments/files/17294961/idea.log)

**Comment by dinbtechit** [comment]
I was able to reproduce the issue. I will try to fix this in the next release. I am in the middle of switching jobs so please bare with me.

**Comment by dinbtechit** [comment]
Fixed in v0.0.3
